#!/bin/bash

## variables to be moved to .env file

#USERNAME="elastic"
#PASSWORD="8xP3984vNgl9uIauv5chV396"
#URL="node02:9200"
source .env

## function with jquery
function es_request {
  curl -s -H "Content-Type: application/json" -k -u $USERNAME:$PASSWORD -$1 "https://$URL/$2" |jq 
}
## function without jquery
function request {
  curl -s -H "Content-Type: application/json" -k -u $USERNAME:$PASSWORD -$1 "https://$URL/$2" 
}
## function PUT|POST 
function p_request {
  curl -s -H "Content-Type: application/json" -k -u $USERNAME:$PASSWORD -$1 "https://$URL/$2" -d @$3 |jq 
}

## variables to work in requests

OPT=$1
QUERY=$2
  if [ -z $1 ]; then
    OPT=""
    echo "error"
  elif [ -n $1 ]; then
    OPT=$1
    QUERY=$2
  fi
FILE=$3

## options use
  case $OPT in
    GET|get)
     QUERY=$2
     FILE=$3
     if [[ "$QUERY" =~ _cat/indices.*$ ]]; then
	    request XGET $QUERY
     elif [ -z $FILE ]; then 
     # do_option_1
     #[ -z $QUERY ] && { echo "wrong option"; exit 1; } || esrequest XGET $QUERY |jq 
     es_request XGET $QUERY 
     else
	     p_request XGET $QUERY $FILE
     fi
     #echo GET
    ;;
    PUT|put)
     # do_option_2
     prequest $OPT $QUERY $FILE
    ;;
    POST|post)
     # do_option_2
    request XPOST $QUERY $FILE
    ;;
    DELETE|del|delete)
     # do_option_2
    request XDELETE $QUERY
    ;;
    help)
      echo "Usage GET PUT POST DELETE endpoint"
    ;;
    *)
      echo "wrong option, use GET|PUT|POST|DELETE endpoint"
      echo " ";
      echo "Example usage:";
      echo "es-query GET _cat/indices?pretty";
      echo " ";
    ;;
  esac
  shift
